In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential

In [3]:
reviews = [
    # Positive sentiments
    "nice food",
    "great",
    "too good",
    "excellent service",
    "amazing experience",
    "delicious food",
    "very tasty",
    "friendly staff",
    "highly recommended",
    "really enjoyed it",
    "wonderful place",
    "best experience",

    # Negative sentiments
    "horrible food",
    "don't go there",
    "very bad service",
    "terrible experience",
    "food was awful",
    "not worth the money",
    "really disappointed",
    "staff was rude",
    "food tasted terrible",
    "would not recommend",
    "very poor quality",
    "worst experience"
]

In [5]:
sentiment = [1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0]

In [8]:
vocab_size = 30 #in here 30 is just a random number
encoded_reviews = [one_hot(d , vocab_size) for d in reviews]
encoded_reviews

[[8, 4],
 [8],
 [19, 7],
 [16, 11],
 [29, 23],
 [8, 4],
 [15, 24],
 [29, 27],
 [25, 9],
 [29, 21, 12],
 [12, 20],
 [14, 23],
 [16, 4],
 [24, 15, 23],
 [15, 2, 11],
 [5, 23],
 [4, 27, 28],
 [1, 2, 5, 18],
 [29, 29],
 [27, 27, 18],
 [4, 29, 5],
 [28, 1, 26],
 [15, 5, 16],
 [1, 23]]

In [9]:
Max_len = 4

In [12]:
padded_reviews = pad_sequences(encoded_reviews , padding='post' , maxlen=Max_len)
padded_reviews

array([[ 8,  4,  0,  0],
       [ 8,  0,  0,  0],
       [19,  7,  0,  0],
       [16, 11,  0,  0],
       [29, 23,  0,  0],
       [ 8,  4,  0,  0],
       [15, 24,  0,  0],
       [29, 27,  0,  0],
       [25,  9,  0,  0],
       [29, 21, 12,  0],
       [12, 20,  0,  0],
       [14, 23,  0,  0],
       [16,  4,  0,  0],
       [24, 15, 23,  0],
       [15,  2, 11,  0],
       [ 5, 23,  0,  0],
       [ 4, 27, 28,  0],
       [ 1,  2,  5, 18],
       [29, 29,  0,  0],
       [27, 27, 18,  0],
       [ 4, 29,  5,  0],
       [28,  1, 26,  0],
       [15,  5, 16,  0],
       [ 1, 23,  0,  0]], dtype=int32)

In [14]:
embeded_vector_size = 5

model = Sequential([
    Embedding(vocab_size , embeded_vector_size , input_length = Max_len),
    Flatten(),
    Dense(1 , activation = "sigmoid")
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
X = padded_reviews
Y = sentiment

In [16]:
model.compile(optimizer="adam" , loss="binary_cross_entropy" , metrics=["accuracy"])

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
history = model.fit(X,Y,epochs=20)

ValueError: Unrecognized data type: x=[[ 8  4  0  0]
 [ 8  0  0  0]
 [19  7  0  0]
 [16 11  0  0]
 [29 23  0  0]
 [ 8  4  0  0]
 [15 24  0  0]
 [29 27  0  0]
 [25  9  0  0]
 [29 21 12  0]
 [12 20  0  0]
 [14 23  0  0]
 [16  4  0  0]
 [24 15 23  0]
 [15  2 11  0]
 [ 5 23  0  0]
 [ 4 27 28  0]
 [ 1  2  5 18]
 [29 29  0  0]
 [27 27 18  0]
 [ 4 29  5  0]
 [28  1 26  0]
 [15  5 16  0]
 [ 1 23  0  0]] (of type <class 'numpy.ndarray'>)

In [ ]:
loss , accuracy = model.evaluate(X , Y)